version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.4
  aws-cli: circleci/aws-cli@4.0
  argocd: papercup-ai/argocd@0.6.0

defaults: &defaults
  docker:
    - image: cimg/python:3.7

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - prepare
      - allow-dev:
          type: approval
          requires:
            - prepare
      - aws-ecr/build_and_push_image:
          name: aws-ecr/build-and-push-image-dev
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::064824517495:role/circleCi_ecr
          context: AWS
          region: $AWS_DEFAULT_REGION
          repo: filter-paper
          tag: $CIRCLE_SHA1
          requires:
            - allow-dev
      - argocd/deploy:
          service: filter-paper
          context: AWS
          argo-token: $ARGOCD__TOKEN
          cluster: papercup-eks-dev
          namespace: papercup-dev
          requires:
            - aws-ecr/build-and-push-image-dev

      - allow-prod:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - prepare
      - aws-ecr/build_and_push_image:
          name: aws-ecr/build-and-push-image-prod
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::064824517495:role/circleCi_ecr
          context: AWS
          region: $AWS_DEFAULT_REGION
          repo: filter-paper
          tag: $CIRCLE_SHA1
          requires:
            - allow-prod
      - argocd/deploy:
          service: filter-paper
          context: AWS
          argo-token: $ARGOCD__TOKEN
          cluster: papercup-eks-prod
          namespace: papercup-prod
          requires:
            - aws-ecr/build-and-push-image-prod
